### ISSUE TITLE
LSMDC16_annos_gender.json/ bert_text_gender_embedding     /face_features_rgb_mtcnn_cluster    

### ISSUE THREAD

**Issue by haoshuai714** [jamespark3922/lsmdc-fillin#1]
I can not found those file, such as :
data/fillin_data/LSMDC16_annos_gender.json                  (gender information for each clip)
data/fillin_data/bert_text_gender_embedding                 (bert trained to do gender classification that will be used to encode the sentence)
data/fillin_data/face_features_rgb_mtcnn_cluster            (face clusters)

Could you tell me how to download this file?

**Comment by jamespark3922** [comment]
Updated download link
