### ISSUE TITLE
Access Denied for Pretrained Checkpoints Link and missing Test Reference Files

### ISSUE THREAD

**Issue by dnaveenr** [jamespark3922/lsmdc-fillin#3]
Hello James,

The link to download the pretrained checkpoints is not accessible.
`wget https://storage.googleapis.com/jamesp/lsmdc/fillin2_transformer_memory9_mtcnn_cluster_gender0.2_bert_gender_sent_emb_bs64_augmented_new_no_img.zip`
**Access is denied** for the following file.

Also, to run the evaluation on the Test Set:
`python eval.py --batch_size 64 --g_model_path {$exp_path}/gen_best.pth  --infos_path {$exp_path}/infos.pkl --id $eval_id --split test`

**references_test_new.csv and testSets.csv are not present** in the https://github.com/jamespark3922/lsmdc-fillin/tree/master/character_eval/input folder.

We're trying to replicate results from your paper, it would be great if you can share these files.

Thank you,
Naveen

**Comment by jamespark3922** [comment]
Hello,

We apologize for the confusion and thank you for pointing it out!
We just fixed the storage link in README, so they should be accessible now.
```
wget https://storage.googleapis.com/ai2-jamesp-public/lsmdc/fillin2_transformer_memory9_mtcnn_cluster_gender0.2_bert_gender_sent_emb_bs64_augmented_new_no_img.zip
```

We do not release a public test set and instead you can submit your predictions via [codalab](https://competitions.codalab.org/competitions/32769) to get the results. We have val results in paper so you can compare the results in val first.
